// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddCube: typeof import('./src/components/DevTools/AddCube.vue')['default']
    ChessBoard: typeof import('./src/components/Playground/ChessBoard.vue')['default']
    ChessBoardCube: typeof import('./src/components/Playground/ChessBoardCube.vue')['default']
    Cover: typeof import('./src/components/Cover.vue')['default']
    CubeComponent: typeof import('./src/components/Playground/CubeComponent.vue')['default']
    DeleteCube: typeof import('./src/components/DevTools/DeleteCube.vue')['default']
    DevTools: typeof import('./src/components/DevTools/DevTools.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Game: typeof import('./src/components/Game/Game.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MoveCube: typeof import('./src/components/DevTools/MoveCube.vue')['default']
    Playground: typeof import('./src/components/Playground/Playground.vue')['default']
    PromptAddCubes: typeof import('./src/components/Playground/PromptAddCubes.vue')['default']
    PromptCubes: typeof import('./src/components/Playground/PromptCubes.vue')['default']
    Score: typeof import('./src/components/Playground/Score.vue')['default']
  }
}

export {}
