// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddCube: typeof import('./src/components/DevTools/AddCube.vue')['default']
    DeleteCube: typeof import('./src/components/DevTools/DeleteCube.vue')['default']
    DevTools: typeof import('./src/components/DevTools/index.vue')['default']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MoveCube: typeof import('./src/components/DevTools/MoveCube.vue')['default']
  }
}

export {}
